version: '3.7'
services:
  mongodb:
    restart: always
    image: mongo:latest
    container_name: "mongodb"
    ports:
    - "27017:27017"
    volumes:
    - 'mongo:/data/mongodb'
  redis:
    restart: always
    image: redis:latest
    container_name: "redis"
    ports:
    - "6379:6379"
    volumes:
    - 'redis:/data/redis'
  neo4j:
    restart: always
    image: neo4j:latest
    container_name: "neo4j"
    ports:
    - "7687:7687"
    - "7474:7474"
    volumes:
    - 'neo4j:/data/neo4j'
  cassandra:
    restart: always
    image: cassandra:latest
    container_name: "cassandra"
    ports:
    - "9042:9042"
    volumes:
    - 'cassandra:/data/cassandra'
volumes:
  mongo:
  redis:
  neo4j:
  cassandra: